name: Build

on: [push, pull_request]

jobs:
  Build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: ["14", "16"]
    runs-on: ${{ matrix.os }}
    name: build and test (${{ matrix.os }}|node-${{ matrix.node }})

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - run: node --version
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier
