name: Deploy

on:
  release:
    types:
      - published

jobs:
  Deploy-To-NPM:
    runs-on: ubuntu-latest
    name: Deploy to NPM

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - run: node --version
      - run: npm ci
      - run: npm run lint
      - run: ls && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
